     name: Ngrok RDP
     on: [push]
     jobs:
       deploy:
         runs-on: ubuntu-latest
         steps:
           - uses: actions/checkout@v2
           - run: |
               sudo apt-get update
               sudo apt-get install ngrok
               ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
               ngrok tcp 3389 &
           - run: |
               sleep 10
               curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'

     
